### PR TITLE
Added notes from Aug 8

### PR DESCRIPTION
**Pull request by RichardLitt**
See #139. cc @nicola @flyingzumwalt

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
I recommend calling the directory meeting-notes instead of just notes. Meeting notes are important enough that they deserve their own directory. It will also make it easier to find them.

**Comment by RichardLitt** [comment]
Good call. Fixed.

**Comment by flyingzumwalt** [comment]
Is this ready to be merged? Are you going to add the notes from the other calls (js-ipfs and libp2p)?

**Comment by RichardLitt** [comment]
It's ready now. Check?

**Pull request merged**
