### PR TITLE
Pm doc draft 2

### PR DESCRIPTION
**Pull request by flyingzumwalt**
Minor text fixes and rearranged outline. Any real re-working and re-wording will happen after #153

### CODE REVIEW

**Comment by jbenet** [comment]
Wonder if using the following emoji would help in this document:

- 📚 Project
- 📘 Milestone
- 📄 Goal

("book stack" contains "books" contains "pages") makes it clear how these relate.

**Comment by haadcode** [comment]
LGTM

**Comment by RichardLitt** [comment]
Want me to make a readability, or alternatively deep, read through?

**Comment by flyingzumwalt** [comment]
Don't worry about readability at this point. We will be re-working almost every section one-by-one over the coming weeks (while testing/applying the model with go-ipfs).  I also intend to completely rearrange the whole thing once we're done with that.

**Comment by flyingzumwalt** [comment]
Ok. Added the emoji.

**Pull request merged**
