### PR TITLE
Move the OKR Planning and Indexing to the same repo

### PR DESCRIPTION
**Pull request by diasdavid**
Following https://github.com/ipfs/project/issues/1

### CODE REVIEW

**Comment by diasdavid** [comment]
Hi there @ipfs/working-group-captains o/ ⚡️

A proposal -- https://github.com/ipfs/project/issues/1 -- was made during the IPFS days for us to consolidate our OKR Open Planning into a single repo so that it is easy to find where everyone is having their discussions, retrospectives (if any) and any other element on how the team is discussing the plan for the next quarter.

I went away and made it for JS Core to test this approach out. I like it!

Can I get you to volunteer and create the doc for each of your Working Groups? I'm aware that not every WG is producing the same docs as the JS Core and that is OK, even if you just link the Spreadsheet tab, that is already great and sets us for planning next quarter.

**Comment by olizilla** [comment]
I'm gonna add the ipfs-gui OKR doc to this branch.

**Comment by momack2** [comment]
Added the go-ipfs OKR docs!

**Comment by pgte** [comment]
Just pushed DDC OKRs.

**Comment by diasdavid** [comment]
Thank you everyone that has pushed their OKRs placeholders so far. Now we are just missing:

- [ ] Community, @mikeal 
- [ ] Decentralized Data Stewardship, @meiqimichelle 
- [ ] IPFS in Web Browsers, @lidel 
- [ ] IPFS Cluster, @hsanjuan 
- [ ] IPFS Infrastructure, @eefahy

**Comment by lidel** [comment]
Just added in-web-browsers one :)

**Comment by eefahy** [comment]
Added Infra OKRs

**Comment by vmx** [comment]
@diasdavid Ooups. I read the list of projects missing after pushing my commit. Aren't the IPLD OKRs supposed to be here. Given there's no ipld/pm repo, I guess this repo makes sense.

**Comment by diasdavid** [comment]
@vmx that's fine by me, although I believe some folks would prefer to kick off IPLD as a separate org.

**Comment by diasdavid** [comment]
I'll go ahead and merge this one, leaving the two outstanding ones as issues

**Pull request merged**
