### PR TITLE
Remove lead from templates, other edits

### PR DESCRIPTION
**Pull request by RichardLitt**
I think having a lead for each call gives the wrong impression of the scope of each project. For instance, @haadcode isnt the only person who can handle Apps on IPFS. As well, it stops others from jumping in to facilitate these calls. Finally, in at least the All hands call, it rotates, and I think it should in the others. I have removed it in this PR.

I have also removed the extra time zone markings, which are in the column, and removed bold from the UTC timezone (which did not show up in the markdown, anyway), and added the word agenda to the notes to make it clearer what that link points to. Overall, I think this is now a cleaner template for the sprints.

Finally, I moved IPLD to Friday, and added a Monday and a Friday section to make this clearer.

### CODE REVIEW

**Comment by diasdavid** [comment]
well, fair point, but also getting the name there in the first comment and with a tag was a very good way to make sure that person was signalled to remember their responsibility

**Comment by RichardLitt** [comment]
That is a good point for this. Is putting it here the best way to do that? We could also add names at the bottom of the list, or we could automatically assign the issue to the leads.

**Comment by RichardLitt** [comment]
We could also change the "Lead" to "Moderator". This raises a point; should the moderator for these calls be the lead? Or should we rotate, as well, even if the lead on the projects is the main person talking?

**Comment by RichardLitt** [comment]
Added it back. Switching the template over.

**Pull request merged**
