### PR TITLE
All hand meeting 2018-05-21 notes

### PR DESCRIPTION
**Pull request by vmx**
The workflow I've used to get things from Google Docs to Markdown.
It's a copy and paste exercise:

 - Copy from Google Docs, paste it into OpenOffice
 - Copy from OpenOffice, paste it into https://stackedit.io/
 - Copy from https://stackedit.io/ and run it through `sed '/^ \s*$/d'`
 - Paste output into Github

### CODE REVIEW

**Comment by vmx** [comment]
@mgoelzer Please double-check the Dev Meetings dates :)

**Comment by Mr0grog** [comment]
…is there any reason this is still open? Can we merge it?

**Comment by mgoelzer** [comment]
LGTM

(Dev Meeting dates are correct in this PR.  I think @vmx was referring to the source google doc, which probably had an error but has since been corrected and converted to markdown.)

**Comment by Mr0grog** [comment]
I’ll go ahead and merge it, then!

**Pull request merged**
