### PR TITLE
Removed permalink column

### PR DESCRIPTION
**Pull request by RichardLitt**
No longer needed.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
You can drop testing, bitswap, data structures and protocol from the template as well

**Comment by RichardLitt** [comment]
Permanently?

**Comment by Dignifiedquire** [comment]
From the base template I think so, they are only added on a needed basis

**Comment by Dignifiedquire** [comment]
Ref https://github.com/ipfs/pm/commit/d7b45e97d11933e8ae80dff7133f2fd90b4bd31d

**Comment by RichardLitt** [comment]
Aight. Doing that now.

**Comment by diasdavid** [comment]
:+1:

**Pull request merged**
