### PR TITLE
(WIP) Generated PM Roadmap

### PR DESCRIPTION
**Pull request by flyingzumwalt**
This PR adds a config file for generating a roadmap for IPFS PM work using haadcode/roadmap-generator. I also added a sample Organization Roadmap too.  KEEP IN MIND that this generated Org Roadmap is incomplete because it only recognizes GH milestones as milestones, _so any project that's using GH labels or GH tickets to represent milestones will be missed from this Org Roadmap._

@haadcode this generator is awesome.

@em-ly @RichardLitt how do you feel about using this roadmap as a frame for figuring out where we need to create Milestones in order to make everyone's PM and community-related work visible?
- ORG-ROADMAP.md: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/ORG-ROADMAP.md
- PM ROADMAP.md: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/ROADMAP.md

Configs for the generator (which tells it which repositories and timeframes to include):
- Org Roadmap Config: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/org-roadmap.conf.js
- PM Roadmap Config: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/roadmap-generator.conf.js

ref #135

### CODE REVIEW

**Comment by lgierth** [comment]
That roadmap looks reeally good

**Comment by flyingzumwalt** [comment]
Added a sample Organization Roadmap too

* ORG-ROADMAP.md: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/ORG-ROADMAP.md
* PM ROADMAP.md: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/ROADMAP.md

Configs for the generator (which tells it which repositories and timeframes to include):
* Org Roadmap Config: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/org-roadmap.conf.js
* PM Roadmap Config: https://github.com/ipfs/pm/blob/623fdf1f54547ba7dcd697bed20fe8cdc9d1b1e9/roadmap-generator.conf.js

**Comment by RichardLitt** [comment]
I don't understand some of the terms here (what is the rocket ship? What does ready mean?). Where can I find a write up that summarizes this?

**Comment by flyingzumwalt** [comment]
@RichardLitt I'm pretty sure the labels (like `ready`) are just a list of from GH labels, so it's up to us to define those terms.  The rocketship, etc. are just an experiment.  The mappings are in the roadmap-generator code [here](https://github.com/haadcode/roadmap-generator/blob/master/index.js#L47-L57), which includes comments with some alternatives.  For usability/accessibility I think these need to be words instead of emoji.

All of that stuff is just a WIP. @whyrusleeping suggested that it might be better for the generator to make a json file instead of a markdown file so we have more options for display, but golly I do like the simplicity of having a ROADMAP.md right there in your repo, with git tracking how it changes over time.

**Comment by haadcode** [comment]
Looking good @flyingzumwalt! 

Seeing the roadmaps generated for more projects and by someone else is great, puts everything into perspective :) 

I think we should tweak the general visuals of the document: the relation between the header sizes and the rest of the milestone texts, the description (instead of quote, maybe just a paragraph, maybe in italics?), the emojis, etc. I agree we should use text instead of emojis (at least for the "Status" column in the milestone summary).

> any project that's using GH labels or GH tickets to represent milestones will be missed from this Org Roadmap

I still want to do this, but unfortunately I won't have time before end of the month :/

>  @whyrusleeping suggested that it might be better for the generator to make a json file instead of a markdown file so we have more options for display

It's actually already a JSON that just gets formatted into Markdown at the end: https://github.com/haadcode/roadmap-generator/blob/master/index.js#L295 (`final` is the json data). Adding an option to export the roadmap as json instead of Markdown is trivial, so if we *really* need this, let me know or open an issue in the repo and I can add it. 

> golly I do like the simplicity of having a ROADMAP.md right there in your repo, with git tracking how it changes over time.

YES! 💯 👍 This was the whole idea of the generator :) Aaaand, some day, we will have it completely automated so that you don't need to run it manually/locally. You should only need to edit the config files (and obviously your projects' issues and milestones).

**Comment by RichardLitt** [comment]
I also want something I can track in git. That sounds good. 

> The rocketship, etc. are just an experiment.

I honestly don't know what 'ready' means; is this project roadmap going to be used together with Waffle? 

I think I may just need a higher level document outlining this; @flyingzumwalt, can we have a video chat about your vision for this roadmap?

**Comment by flyingzumwalt** [comment]
I'd like to practice conducting conversations like this async as much as possible. Let's add it to the agenda for Monday's all-hands and then see if we need more synchronous discussion after that.

Regarding the fact that the label 'ready' appears in the roadmap, that's just because the roadmap is listing all of the labels attached to each GH issue. I think is useful to list the labels there.  Every project has the freedom to define their own labels as they see fit, but waffle creates a "ready" label for its default "ready" column. That's why the 'ready' label shows up so much in the generated roadmap.

Regarding the definition of ready, I agree that it needs to be addressed in the PM document. See #169, which is part of the [milestone for implementing the new PM process](https://github.com/ipfs/pm/milestone/1).

**Comment by diasdavid** [comment]
Shall we drop this one now that we have the OKR/Working Group strategy?

**Comment by diasdavid** [comment]
I'm closing this one as we don't use the tooling nor the process anymore in favor of OKRs + Working Groups + Each Project with their own tracking strategy. For reference, check:

- Working Groups Proposal and Discussion - https://github.com/ipfs/ipfs/pull/285
- js-ipfs Tracking - https://github.com/ipfs/js-ipfs/blob/master/MGMT.md
- OKRs for Q2 https://docs.google.com/spreadsheets/u/1/d/1xIhKROxFlsY9M9on37D5rkbSsm4YtjRQvG2unHScApA/edit#gid=534051604

**Pull request closed without merging**
