### PR TITLE
Add js-notes for today

### PR DESCRIPTION
**Pull request by RichardLitt**
For @diasdavid

### CODE REVIEW

**Comment by diasdavid** [comment]
# Enumerate all the tests for the new ipfsd-ctl https://github.com/ipfs/js-ipfsd-ctl/issues/95 @jbenet

**Comment by diasdavid** [comment]
# @jbenet to follow up on https://github.com/ipfs/specs/issues/98

**Comment by RichardLitt** [comment]
@diasdavid Status?

**Comment by diasdavid** [comment]
rfm

**Pull request merged**
