### PR TITLE
PROPOSAL: Move sprint planning to start at 17:15 UTC (mondays)

### PR DESCRIPTION
**Pull request by jbenet**
It's difficult for people in Germany to join the day's conversations
if they are so late. this would be better for them, i think.

How does everyone feel about this? please respond with either:
- :+1:
- :-1: \<reason>

### CODE REVIEW

**Comment by whyrusleeping** [comment]
:+1:

**Comment by whyrusleeping** [comment]
(although I don't think @jbenet can be awake at 17:00Z)

**Comment by cryptix** [comment]
:+1: (could be that I miss the checkins some time but i can send in my part by mail or post it on gh on the last one)

**Comment by diasdavid** [comment]
:+1: 

> (although I don't think @jbenet can be awake at 17:00Z)

Jeromy has a point :P

**Comment by lgierth** [comment]
:+1:

**Comment by jbenet** [comment]
> > (although I don't think @jbenet can be awake at 17:00Z)
> Jeromy has a point :P

Maybe I wont have to wake up. Maybe i'll be _still awake_!

**Comment by jbenet** [comment]
I think that's enough agreement. can sync with others asynchronously thorughout the day if the earlier checkin in time is no good for them.

**Pull request merged**
